services:
  spotify-remote:
    build: .
    container_name: spotify-remote
    network_mode: host
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - PORT=${PORT:-5000}
    restart: unless-stopped
    volumes:
      - spotify_cache:/app/.cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  spotify_cache:
    driver: local 