version: '3.8'

services:
  spotify-remote:
    build: .
    container_name: spotify-remote-prod
    network_mode: host
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - REDIRECT_URI=${REDIRECT_URI}
      - DOMAIN_NAME=${DOMAIN_NAME:-}
      - PORT=${PORT:-5000}
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY:-}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME:-spotify-remote}
      - FLASK_ENV=production
    volumes:
      # Mount Spotify cache directory for persistent tokens
      - spotify_cache:/app/.cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Production security settings
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

volumes:
  spotify_cache:
    driver: local 