services:
  spotify-remote:
    build: .
    container_name: spotify-remote
    ports:
      - "5000:5000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - REDIRECT_URI=${REDIRECT_URI}
      - USE_HTTPS=${USE_HTTPS:-true}
      - DOMAIN_NAME=${DOMAIN_NAME:-}
      - CERT_PATH=${CERT_PATH:-./certs}
      - PORT=${PORT:-5000}
      - TAILSCALE_AUTH_KEY=${TAILSCALE_AUTH_KEY:-}
      - TAILSCALE_HOSTNAME=${TAILSCALE_HOSTNAME:-spotify-remote}
      - DOCKER_CONTAINER=true
    restart: unless-stopped
    volumes:
      - ./certs:/app/certs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - spotify-network

networks:
  spotify-network:
    driver: bridge 